### ISSUE TITLE
Add support for NVIDIA's open gpu kernel modules

### ISSUE THREAD

**Issue by CCF100** [Frogging-Family/nvidia-all#103]
https://github.com/NVIDIA/open-gpu-kernel-modules

**Comment by Tk-Glitch** [comment]
Added with https://github.com/Frogging-Family/nvidia-all/commit/fa920eb9059907b70c9798e901eccb3dff08e601

**Comment by flindeberg** [comment]
Sorry for pinging a closed issue, but does anyone have any links to performance tests?

**Comment by Tk-Glitch** [comment]
Afaik and outside of missing features, there's exactly zero performance difference.

**Comment by fidasx** [comment]
> Afaik and outside of missing features, there's exactly zero performance difference.

here you go
https://www.phoronix.com/scan.php?page=article&item=nvidia-r515-open&num=1

**Comment by fidasx** [comment]
> Sorry for pinging a closed issue, but does anyone have any links to performance tests?

https://www.phoronix.com/scan.php?page=article&item=nvidia-r515-open&num=1
