### ISSUE TITLE
nvidia-tkg.hook failed to verify

### ISSUE THREAD

**Issue by stjyoon** [Frogging-Family/nvidia-all#107]
When validating source files, nvidia-tkg.hook fails to validate. 

`Validating source files with md5sums...
    NVIDIA-Linux-x86_64-515.43.04.run ... Passed
    10-nvidia-drm-outputclass.conf ... Passed
    nvidia-utils-tkg.sysusers ... Passed
    60-nvidia.rules ... Passed
    nvidia-tkg.hook ... FAILED
    linux-version.diff ... Passed
    01-ipmi-vm.diff ... Passed
    02-ipmi-vm.diff ... Passed
    list_is_first.diff ... Passed
    kernel-4.16.patch ... Passed
    kernel-4.19.patch ... Passed
    kernel-5.0.patch ... Passed
    kernel-5.1.patch ... Passed
    kernel-5.2.patch ... Passed
    kernel-5.3.patch ... Passed
    kernel-5.4.patch ... Passed
    kernel-5.4-symver.diff ... Passed
    kernel-5.4-prime.diff ... Passed
    kernel-5.5.patch ... Passed
    kernel-5.6.patch ... Passed
    5.6-legacy-includes.diff ... Passed
    5.6-ioremap.diff ... Passed
    kernel-5.7.patch ... Passed
    kernel-5.8.patch ... Passed
    5.8-legacy.diff ... Passed
    kernel-5.9.patch ... Passed
    5.9-gpl.diff ... Passed
    kernel-5.10.patch ... Passed
    kernel-5.11.patch ... Passed
    5.11-legacy.diff ... Passed
    455-crashfix.diff ... Passed
    kernel-5.12.patch ... Passed
    kernel-5.14.patch ... Passed
    kernel-5.16.patch ... Passed
    kernel-5.16-std.diff ... Passed
    kernel-5.17.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
  -> exit cleanup done`

**Comment by rosegayming** [comment]
Fixed by #108

**Comment by stjyoon** [comment]
Thank you
