### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by TechXero** [Frogging-Family/nvidia-all#112]
I am trying to build 510 drivers getting following error
```
  -> No open source kernel module available
  -> Building driver version 510.73.05 on branch regular.
  -> Selected driver integrity check behavior (md5sum or SKIP): 2c381e423082da848b1f6ea1158c69d2
/home/xero/nvidia-all/PKGBUILD: line 330: syntax error near unexpected token `('
/home/xero/nvidia-all/PKGBUILD: line 330: `           .---.`               `.---.'
==> ERROR: Failed to source /home/xero/nvidia-all/PKGBUILD
```

Goal is to build 510 drivers and host on my repo if possible... As the 515 ones now being distributed are currently "Beta" on nVidia's official site not Final, and causing issues for a lot of users with older than Turing cards and games no longer running, heavy glitches and more..

**Comment by Tk-Glitch** [comment]
I couldn't reproduce the issue on my end with a clean clone.
Did you run `updpkgsums` maybe? You may have garbage in your PKGBUILD if you did.
Doing so allows me to reproduce your exact issue, so I believe this is it.

**Comment by TechXero** [comment]
Yep that was it... All good now! Thanks. Packages built and in my repo...

**Comment by Tk-Glitch** [comment]
Great news! Enjoy :)

**Comment by TechXero** [comment]
Thanks... You saved my behind... No one else making 510 packages. My Distro is first to have them separately

**Comment by Tk-Glitch** [comment]
Already? That's weird, 515 is beta and quite unstable, it shouldn't be the default.. :/

**Comment by TechXero** [comment]
Yeah am gonna be on DT podcast soon will make my voice heard about subject. My Distro is XeroLinux btw...
