### ISSUE TITLE
Nothing but v.470 is working on my end

### ISSUE THREAD

**Issue by mozo78** [Frogging-Family/nvidia-all#121]
Hello,
I'm using nvidia-all for years without any problems at all but now I have a problem. It seems I have a black screen with any  version newer than 470. If I install a newer version, after the reboot it stucks on "starting version 251..." and that's it. It waits forever but nothing happens. The driver installation is working fine and gives no errors. I tried with the open source module and without it to no avail. Now I'm stuck with 470 - the only version which allows me to reach my desktop graphically. I have a backup and I'm not worried at all but I'm wondering what could be the problem?
Thank you for your hard work and great projects!

**Comment by Tk-Glitch** [comment]
Would you happen to have an Alderlake CPU?

**Comment by Tk-Glitch** [comment]
Also, on which GPU?

**Comment by mozo78** [comment]
I'm with 9900K and GTX 1080Ti :)

**Comment by Tk-Glitch** [comment]
Ok so that shouldn't require anything fancy.. Weird. No failure in dkms? Using a custom kernel?

**Comment by mozo78** [comment]
Nope, It's even not the LTS. It's the default kernel.

**Comment by mozo78** [comment]
Yep, X11. I never tried Wayland because of NVIDIA.

**Comment by Tk-Glitch** [comment]
Do you have a `/etc/X11/xorg.conf` and/or some nvidia.conf in `/etc/X11/xorg.conf.d/`, it might be worth deleting it/them.

**Comment by mozo78** [comment]
Yes, I have /etc/X11/xorg.conf:
https://pastebin.com/B9z59vua

I'm using this config for years with no problems. I have a dual boot with Mint and it's working fine there too but I'm not using it. It's just for game testing :)

**Comment by mozo78** [comment]
I found it:
https://bugs.archlinux.org/task/74886
https://bugs.archlinux.org/task/74891

All is working fine now :)
