### ISSUE TITLE
Question: How do I reduce the size of the nvidia-utils file?

### ISSUE THREAD

**Issue by Orangian** [Frogging-Family/nvidia-all#14]
Hi. I'm building this driver for my personal Arch distro, but the nvidia-utils package file generated is over 100 megabytes which is causing some issues with my package repo. Is there any way to reduce the size of the generated file?

**Comment by Tk-Glitch** [comment]
The only way is to skip some features.
Commenting out the `libnvoptix` & `libnvidia-rtcore` lines in the PKGBUILD would reduce the size by about half, if you're okay without those features.

**Comment by Orangian** [comment]
Ah, thanks! That should get everything working now. Thanks for your help!

**Comment by Tk-Glitch** [comment]
You're welcome!

**Comment by telans** [comment]
> The only way is to skip some features.

Needs some USE flags 😎
