### ISSUE TITLE
6.2 patch fails

### ISSUE THREAD

**Issue by jaypgriff** [Frogging-Family/nvidia-all#140]
just updated repo and it fails to build:

`kernel-6.2.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
-> exit cleanup done`

many thx

**Comment by anonish** [comment]
> `kernel-6.2.patch ... FAILED ==> ERROR: One or more files did not pass the validity check! -> exit cleanup done`
the PKGBUILD was not updated on the last patch
change line 392 (the md5sum array) to

` '5d573b1aa0712b9bd2000c9fefdf84c2')`

you can check the md5sum yourself on patches/kernel-6.2.patch

**Comment by Tk-Glitch** [comment]
I'll fix when I'm home later today. If someone wants to make a PR before that though, feel free to do so.
