### ISSUE TITLE
 nvidia-tweaks; would it make any sense to use it?

### ISSUE THREAD

**Issue by eclass4learning** [Frogging-Family/nvidia-all#142]
Hey guys!

Just wondering if it would make any sense to use this "nvidia-tweaks" along with the tkg nvidia-all package?

This is the package "nvidia-tweaks" package:

https://github.com/ventureoo/nvidia-tweaks

**Comment by ryanmusante** [comment]
@eclass4learning 
I do. check out the other gits up on t

**Comment by eclass4learning** [comment]
> @eclass4learning I do. check out the other gits up on ventureoo

Ah! interesting, i will have a look around! thnaks for the tip!
