### ISSUE TITLE
error patching file when installing 525.85.05

### ISSUE THREAD

**Issue by pppbb** [Frogging-Family/nvidia-all#145]
-> Applying kernel-6.2.patch for 6.2.0-rc4-273-tkg-cfs...
patching file nvidia-drm/nvidia-drm-connector.c
Hunk #2 FAILED at 100.
Hunk #3 succeeded at 117 (offset 5 lines).
1 out of 3 hunks FAILED -- saving rejects to file nvidia-drm/nvidia-drm-connector.c.rej
patching file nvidia-drm/nvidia-drm-drv.c
Hunk #2 FAILED at 258.
1 out of 2 hunks FAILED -- saving rejects to file nvidia-drm/nvidia-drm-drv.c.rej
==> BŁĄD: Wystąpił błąd w prepare().
    Przerywam...
  -> exit cleanup done

**Comment by anonish** [comment]
per
https://rglinuxtech.com/?p=3088


nvidia 525.78+ (including the new one) do not need the patch anymore.  I built it fine by changing line 789 in PKGBUILD to 
525.6* (from 525.*)


```
# 6.2
      if (( $(vercmp "$_kernel" "6.2") >= 0 )); then
        _kernel62="1"
        _whitelist62=( 525.6* )
      fi
```
