### ISSUE TITLE
Build error on latest kernel

### ISSUE THREAD

**Issue by Martmists-GH** [Frogging-Family/nvidia-all#150]
Compilation terminates with `fatal error: generated/autoconf.h: no such file or directory` from `././include/Linux/kconfig.h:5:10`

**Comment by Tk-Glitch** [comment]
Make sure you have kernel headers installed for all currently installed kernels.

**Comment by Martmists-GH** [comment]
I had the kernel headers installed, but it seems while the dkms modules were present (even during reinstall of linux-headers) it would always remove the autoconf header. Removing the dkms modules and rebooting, then reinstalling headers and rebooting, and finally reinstalling dkms modules solved the issue.
