### ISSUE TITLE
Wayland refresh rate black screen

### ISSUE THREAD

**Issue by RephlexZero** [Frogging-Family/nvidia-all#154]
I have two monitors, I use linux-lqx and nvidia-all 530.30.02 on Gnome Wayland EndeavourOS.
I have an RTX 3070.

When my main monitor (Pixio PX277P 1440p 165Hz) is set above 60Hz, it goes completely black with no signal, this doesn't effect my secondary monitor and wasn't observed on driver version 525.89.02.

X11 works fine though, I'm not sure what info you'd like here, but I'll reply asap, cheers.

**Comment by ptr1337** [comment]
I think it would be better to report this issue to nvidia itself. Here is not the correct place for if it worked in a previous version.
The 530 drivers are also a beta driver, so just report to them
