### ISSUE TITLE
Add option value for selecting the latest driver

### ISSUE THREAD

**Issue by CodingKoopa** [Frogging-Family/nvidia-all#19]
I usually just want the latest regular driver, so, it would be nice if we could just set `_driver_version` to something like `latest` in the configuration file.

**Comment by Tk-Glitch** [comment]
Latest what? long-lived, short-lived, vulkan-dev? Date can be misleading due to legacy branches getting updates sometimes.

**Comment by CodingKoopa** [comment]
I'm afraid I don't understand Nvidia's release system much, but I suppose either short-lived or vulkan-dev depending on `_driver_branch`.
