### ISSUE TITLE
545.23.06 Beta

### ISSUE THREAD

**Issue by Grimish-ng** [Frogging-Family/nvidia-all#191]
A bunch of new features are being added so maybe some clerification if anyone is aware. 

Error out on egl-wayland. Is that version correct or should I be adding something different to the PKGBUILD?

install: cannot stat 'libnvidia-egl-wayland.so.1.1.11': No such file or directory
==> ERROR: A failure occurred in package_nvidia-egl-wayland-tkg().

**Comment by Tk-Glitch** [comment]
That's 1.1.12. Did you update to https://github.com/Frogging-Family/nvidia-all/commit/e04ae89384d5a4ca9f061112ca3c989a36215d27 ?

**Comment by Grimish-ng** [comment]
My bad. Should have pulled first. Thanks.
