### ISSUE TITLE
470xx Updates?

### ISSUE THREAD

**Issue by DarkXero-dev** [Frogging-Family/nvidia-all#201]
New 470xx drivers released, any chance to get them in nvidia-all for Kernel 6.6.x ?
https://www.nvidia.com/download/driverResults.aspx/215840/en-us/

Humble thanks keep it up you guys.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/nvidia-all/commit/7463f601e7b0c88e08470cdacbc5aed6c17eaa9e
