### ISSUE TITLE
Integrity checks (md5) differ in size from the source array

### ISSUE THREAD

**Issue by erri120** [Frogging-Family/nvidia-all#202]
Running `makepkg -si` and selecting the `535.129.03` driver results in this error:

```
Integrity checks (md5) differ in size from the source array
```
Commit is 7463f601e7b0c88e08470cdacbc5aed6c17eaa9e.

**Comment by Tk-Glitch** [comment]
https://github.com/Frogging-Family/nvidia-all/commit/219d3a00776b7af7b0522ddbb996696691303bb8 Should have fixed this as well
