### ISSUE TITLE
Getting 404 when trying to download 470 driver

### ISSUE THREAD

**Issue by r4-broadcast** [Frogging-Family/nvidia-all#204]
Hi, I have a GT 730m card that needs the 470 driver to work. I tried to use this tool to download it, but I'm getting a 404 error:

`  -> Downloading nvidia-open-dkms-tkg-470.223.02.tar.gz...`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`curl: (22) The requested URL returned error: 404`
`==> ERROR: Failure while downloading https://github.com/NVIDIA/open-gpu-kernel-modules/archive/refs/tags/470.223.02.tar.gz`
`    Aborting...`
`  -> exit cleanup done`

**Comment by Tk-Glitch** [comment]
Did you make any change to the config? Were you prompted to use the open driver?
Because there is no open 470 driver, which is why it fails. Either our open availability check fails or we need to add some more safeguards.
