### ISSUE TITLE
 535.43.20 vulkan

### ISSUE THREAD

**Issue by ElecTwix** [Frogging-Family/nvidia-all#209]
The new version of Vulkan Beta drivers has been released.
Could you add?
it is claimed to fix Gamescope.

**Comment by Tk-Glitch** [comment]
It should work through the custom version option until I add it myself.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/nvidia-all/commit/c45b56f2d0c3d72d36486ebc7fca69c6a33cc637
