### ISSUE TITLE
535 series - 535.146.02 is out

### ISSUE THREAD

**Issue by hunabku94** [Frogging-Family/nvidia-all#211]
Hey, 535.146.02 is out for 535 series

**Comment by ryanmusante** [comment]
I wish Phoronix would do some benchmarks on the vulkan dev branch vs regular

**Comment by Tk-Glitch** [comment]
Added with https://github.com/Frogging-Family/nvidia-all/commit/deb4ac2dc2f019d7d5440304a7d43b6baf14f389
