### ISSUE TITLE
kernel-6.8.patch with nvidia-525 

### ISSUE THREAD

**Issue by ProgAchr** [Frogging-Family/nvidia-all#228]
Today, after pacman system udpate kernel 6.8.1 to kernel 6.8.2, i end up  with non bootable system. Luckily, i was use able to chroot and downgrade the kernel.
 
My current Nvidia driver 550.67, but i want to use Nvidia driver 525.147.05 since the game i play the most is much more stable with that driver (rare crash compared to most other version).
installing nvidia 525.147.05 on arch kernel 6.8.1 does not work well.

I think this link is useful to add to you great tool https://aur.archlinux.org/cgit/aur.git/tree/kernel-6.8.patch?h=nvidia-525xx-utils

**Comment by mkfyi** [comment]
I can confirm this. Had to downgrade my kernel as well in order to load the nvidia modules. Looking forward for a fix
