### ISSUE TITLE
Open Source driver is used when told not to

### ISSUE THREAD

**Issue by BlueGoliath** [Frogging-Family/nvidia-all#238]
On 555 the Open Source variant is used even when a user inputs "N" when prompted during install.

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue. Did you make any edit to `customization.cfg` ?

**Comment by Tk-Glitch** [comment]
Sadly that's a kernel boot parameter and that'll depend on your bootloader. That's not really something we can add on our end.
