### ISSUE TITLE
Building driver version 555.42.02 on branch regular

### ISSUE THREAD

**Issue by iceMongus** [Frogging-Family/nvidia-all#240]
I got
==> Starting package_nvidia-dev-utils-tkg()...
sed: couldn't close /home/icem0nger/mnt/tools/!DeV/nvidia-all/pkg/nvidia-utils-tkg/usr/lib/systemd/system/sed5oAoFw: Permission denied
Aborting...

if i use:
sudo makepkg -si
got
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

thank you for help in advance

**Comment by kddlb** [comment]
Do not run makepkg with sudo. It will run sudo by itself when installing the package.

**Comment by iceMongus** [comment]
real SSDBiOSTAR 500Gb with ext4

**Comment by Tk-Glitch** [comment]
Great! Cool that it was a simple fix this time ^^
