### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by Horuyuki** [Frogging-Family/nvidia-all#25]
Have been experiencing a lot of screen tearing in media playback and scrolling of websites. What could be the problem? Installed version is 455, GTX 980TI for the card.

**Comment by Tk-Glitch** [comment]
If you're not using your 980Ti through an intel iGPU (PRIME), the usual fix is to enable composition pipeline (not full composition pipeline) in your nvidia control panel.

**Comment by Horuyuki** [comment]
Thanks, did some further research, was finally able to enable composition pipeline in the end.

**Comment by Horuyuki** [comment]
Thanks, did some further research, was finally able to enable composition pipeline in the end. And tearing is gone by now!

**Comment by Horuyuki** [comment]
Thanks, did some further research, was finally able to enable composition pipeline in the end. And tearing is gone by now!
