### ISSUE TITLE
555.58.02 Released

### ISSUE THREAD

**Issue by 1nikolas** [Frogging-Family/nvidia-all#251]
Driver 555.58.02 (bugfix) has been released

https://www.nvidia.com/Download/driverResults.aspx/228410/en-us/

Thanks

**Comment by pipes80-collab** [comment]
Good, but this driver solve the dims problem with 6.10-rc?

**Comment by ptr1337** [comment]
> Good, but this driver solve the dims problem with 6.10-rc?

There is no problem with 6.10 since a while. Latest 555.58 works fine and also latest 550.90.

**Comment by pipes80-collab** [comment]
Not for me, I can't load dims modules with 6.10-rc2

**Comment by ptr1337** [comment]
> Not for me, I can't load dkms modules with 6.10-rc2

That appears to be an issue in your configuration or equal. We are building the NVIDIA Module since the first release of 555 and also several other users are using it without any problems.

**Comment by Tk-Glitch** [comment]
Closed with https://github.com/Frogging-Family/nvidia-all/commit/4d2be0fa0937daa69d6bb7af1e322bba0fb358fe

**Comment by pipes80-collab** [comment]
Maybe, because I have no problem with Linux kernel 6.9.8 from arch repository
