### ISSUE TITLE
Script is not working.

### ISSUE THREAD

**Issue by sammaji** [Frogging-Family/nvidia-all#259]
I don't know if I'm missing something, but after running the script and rebooting, the nvidia drivers are not loaded.

nvidia-smi says:
> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Comment by eputty123** [comment]
Did you select to use the dkms modules? Could be as simple as setting it up wasn't completed if you didn't use them.
