### ISSUE TITLE
Linux 5.12 - DKMS module isn't compiling

### ISSUE THREAD

**Issue by pkejval** [Frogging-Family/nvidia-all#37]
Logfile:

> DKMS make.log for nvidia-465.24.02 for kernel 5.12.0-150-tkg-bmq (x86_64)
St 28. dubna 2021, 09:14:23 CEST
make[1]: Vstupuje se do adresáře „/usr/lib/modules/5.12.0-150-tkg-bmq/build“
  SYMLINK /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-kernel.o
  SYMLINK /var/lib/dkms/nvidia/465.24.02/build/nvidia-modeset/nv-modeset-kernel.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-peermem/nvidia-ib-peermem-stub.o
  LD [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-ib-peermem-stub.o
 CONFTEST: set_pages_uc
 CONFTEST: hash__remap_4k_pfn
 CONFTEST: list_is_first
 CONFTEST: set_memory_uc
 CONFTEST: set_memory_array_uc
 CONFTEST: set_pages_array_uc
 CONFTEST: acquire_console_sem
 CONFTEST: console_lock
 CONFTEST: ioremap_cache
 CONFTEST: ioremap_wc
 CONFTEST: sg_alloc_table
 CONFTEST: acpi_walk_namespace
 CONFTEST: pci_get_domain_bus_and_slot
 CONFTEST: get_num_physpages
 CONFTEST: efi_enabled
 CONFTEST: pde_data
 CONFTEST: proc_remove
 CONFTEST: pm_vt_switch_required
 CONFTEST: xen_ioemu_inject_msi
 CONFTEST: phys_to_dma
 CONFTEST: get_dma_ops
 CONFTEST: dma_attr_macros
 CONFTEST: dma_map_page_attrs
 CONFTEST: write_cr4
 CONFTEST: of_get_property
 CONFTEST: of_find_node_by_phandle
 CONFTEST: of_node_to_nid
 CONFTEST: pnv_pci_get_npu_dev
 CONFTEST: of_get_ibm_chip_id
 CONFTEST: node_end_pfn
 CONFTEST: pci_bus_address
 CONFTEST: pci_stop_and_remove_bus_device
 CONFTEST: pci_remove_bus_device
 CONFTEST: register_cpu_notifier
 CONFTEST: cpuhp_setup_state
 CONFTEST: dma_map_resource
 CONFTEST: backlight_device_register
 CONFTEST: get_backlight_device_by_name
 CONFTEST: timer_setup
 CONFTEST: pci_enable_msix_range
 CONFTEST: kernel_read_has_pointer_pos_arg
 CONFTEST: kernel_write
 CONFTEST: kthread_create_on_node
 CONFTEST: of_find_matching_node
 CONFTEST: dma_direct_map_resource
 CONFTEST: dev_is_pci
 CONFTEST: tegra_get_platform
 CONFTEST: tegra_bpmp_send_receive
 CONFTEST: flush_cache_all
 CONFTEST: vmf_insert_pfn
 CONFTEST: jiffies_to_timespec
 CONFTEST: ktime_get_raw_ts64
 CONFTEST: ktime_get_real_ts64
 CONFTEST: full_name_hash
 CONFTEST: hlist_for_each_entry
 CONFTEST: pci_enable_atomic_ops_to_root
 CONFTEST: vga_tryget
 CONFTEST: iterate_fd
 CONFTEST: pgprot_decrypted
 CONFTEST: seq_read_iter
 CONFTEST: unsafe_follow_pfn
 CONFTEST: address_space_init_once
 CONFTEST: kbasename
 CONFTEST: vzalloc
 CONFTEST: wait_on_bit_lock_argument_count
 CONFTEST: bitmap_clear
 CONFTEST: usleep_range
 CONFTEST: radix_tree_empty
 CONFTEST: radix_tree_replace_slot
 CONFTEST: pnv_npu2_init_context
 CONFTEST: cpumask_of_node
 CONFTEST: drm_dev_unref
 CONFTEST: drm_reinit_primary_mode_group
 CONFTEST: get_user_pages_remote
 CONFTEST: get_user_pages
 CONFTEST: drm_atomic_state_ref_counting
 CONFTEST: drm_gem_object_lookup
 CONFTEST: drm_atomic_helper_connector_dpms
 CONFTEST: drm_driver_has_gem_prime_res_obj
 CONFTEST: drm_connector_funcs_have_mode_in_name
 CONFTEST: drm_framebuffer_get
 CONFTEST: drm_gem_object_get
 CONFTEST: drm_dev_put
 CONFTEST: drm_format_num_planes
 CONFTEST: drm_connector_for_each_possible_encoder
 CONFTEST: drm_rotation_available
 CONFTEST: drm_vma_offset_exact_lookup_locked
 CONFTEST: drm_gem_object_put_unlocked
 CONFTEST: is_export_symbol_gpl_of_node_to_nid
 CONFTEST: is_export_symbol_gpl_sme_active
 CONFTEST: is_export_symbol_present_swiotlb_map_sg_attrs
 CONFTEST: is_export_symbol_present_swiotlb_dma_ops
 CONFTEST: is_export_symbol_present___close_fd
 CONFTEST: is_export_symbol_present_close_fd
 CONFTEST: is_export_symbol_present_get_unused_fd
 CONFTEST: is_export_symbol_present_get_unused_fd_flags
 CONFTEST: is_export_symbol_present_nvhost_get_default_device
 CONFTEST: is_export_symbol_present_nvhost_syncpt_unit_interface_get_byte_offset
 CONFTEST: is_export_symbol_present_nvhost_syncpt_unit_interface_get_aperture
 CONFTEST: is_export_symbol_present_tegra_dce_register_ipc_client
 CONFTEST: is_export_symbol_present_tegra_dce_unregister_ipc_client
 CONFTEST: is_export_symbol_present_tegra_dce_client_ipc_send_recv
 CONFTEST: is_export_symbol_present_dram_clk_to_mc_clk
 CONFTEST: is_export_symbol_present_get_dram_num_channels
 CONFTEST: is_export_symbol_present_tegra_dram_types
 CONFTEST: is_export_symbol_present_kthread_create_on_node
 CONFTEST: acpi_op_remove
 CONFTEST: file_operations
 CONFTEST: file_inode
 CONFTEST: kuid_t
 CONFTEST: dma_ops
 CONFTEST: swiotlb_dma_ops
 CONFTEST: noncoherent_swiotlb_dma_ops
 CONFTEST: vm_fault_has_address
 CONFTEST: backlight_properties_type
 CONFTEST: vm_insert_pfn_prot
 CONFTEST: vmf_insert_pfn_prot
 CONFTEST: vm_ops_fault_removed_vma_arg
 CONFTEST: vmbus_channel_has_ringbuffer_page
 CONFTEST: device_driver_of_match_table
 CONFTEST: device_of_node
 CONFTEST: node_states_n_memory
 CONFTEST: kmem_cache_has_kobj_remove_work
 CONFTEST: sysfs_slab_unlink
 CONFTEST: proc_ops
 CONFTEST: timespec64
 CONFTEST: vmalloc_has_pgprot_t_arg
 CONFTEST: acpi_fadt_low_power_s0
 CONFTEST: mm_has_mmap_lock
 CONFTEST: pci_channel_state
 CONFTEST: address_space
 CONFTEST: backing_dev_info
 CONFTEST: mm_context_t
 CONFTEST: vm_fault_t
 CONFTEST: mmu_notifier_ops_invalidate_range
 CONFTEST: drm_bus_present
 CONFTEST: drm_bus_has_bus_type
 CONFTEST: drm_bus_has_get_irq
 CONFTEST: drm_bus_has_get_name
 CONFTEST: drm_driver_has_device_list
 CONFTEST: drm_driver_has_legacy_dev_list
 CONFTEST: drm_crtc_state_has_connectors_changed
 CONFTEST: drm_driver_has_set_busid
 CONFTEST: drm_init_function_args
 CONFTEST: drm_helper_mode_fill_fb_struct
 CONFTEST: drm_master_drop_has_from_release_arg
 CONFTEST: drm_driver_unload_has_int_return_type
 CONFTEST: drm_atomic_helper_crtc_destroy_state_has_crtc_arg
 CONFTEST: drm_mode_object_find_has_file_priv_arg
 CONFTEST: drm_atomic_helper_plane_destroy_state_has_plane_arg
 CONFTEST: dma_buf_owner
 CONFTEST: drm_connector_list_iter
 CONFTEST: drm_atomic_helper_swap_state_has_stall_arg
 CONFTEST: drm_driver_prime_flag_present
 CONFTEST: drm_gem_object_has_resv
 CONFTEST: drm_crtc_state_has_async_flip
 CONFTEST: drm_crtc_state_has_pageflip_flags
 CONFTEST: drm_format_modifiers_present
 CONFTEST: drm_vma_node_is_allowed_has_tag_arg
 CONFTEST: drm_vma_offset_node_has_readonly
 CONFTEST: drm_display_mode_has_vrefresh
 CONFTEST: drm_driver_master_set_has_int_return_type
 CONFTEST: drm_driver_has_gem_free_object
 CONFTEST: drm_prime_pages_to_sg_has_drm_device_arg
 CONFTEST: drm_driver_has_gem_prime_callbacks
 CONFTEST: drm_crtc_atomic_check_has_atomic_state_arg
 CONFTEST: drm_gem_object_vmap_has_map_arg
 CONFTEST: dom0_kernel_present
 CONFTEST: nvidia_vgpu_kvm_build
 CONFTEST: nvidia_grid_build
 CONFTEST: nvidia_grid_csp_build
 CONFTEST: pm_runtime_available
 CONFTEST: pci_class_multimedia_hd_audio
 CONFTEST: drm_available
 CONFTEST: drm_atomic_available
 CONFTEST: is_export_symbol_gpl_refcount_inc
 CONFTEST: is_export_symbol_gpl_refcount_dec_and_test
 CONFTEST: drm_alpha_blending_available
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-frontend.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-pci.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-acpi.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-cray.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-dma.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-i2c.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-mmap.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-p2p.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-pat.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-procfs.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-usermap.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-vm.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-vtophys.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/os-interface.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/os-mlock.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/os-pci.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/os-registry.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/os-usermap.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-modeset-interface.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-pci-table.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-kthread-q.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-memdbg.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-ibmnpu.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-report-err.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-rsync.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-msi.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-caps.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv_uvm_interface.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nvlink_linux.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/nvlink_caps.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/linux_nvswitch.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia/procfs_nvswitch.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_common.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_linux.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/nvstatus.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/nvCpuUuid.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/nv-kthread-q.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/nv-kthread-q-selftest.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_tools.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_global.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_gpu.o
/var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-caps.c: In function ‘nv_cap_close_fd’:
/var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-caps.c:598:5: error: implicit declaration of function ‘sys_close’ [-Werror=implicit-function-declaration]
  598 |     sys_close(fd);
      |     ^~~~~~~~~
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_gpu_isr.o
  CC [M]  /var/lib/dkms/nvidia/465.24.02/build/nvidia-uvm/uvm_procfs.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /var/lib/dkms/nvidia/465.24.02/build/nvidia/nv-caps.o] Chyba 1
make[2]: *** Čeká se na nedokončené úlohy…
make[1]: *** [Makefile:1851: /var/lib/dkms/nvidia/465.24.02/build] Chyba 2
make[1]: Opouští se adresář „/usr/lib/modules/5.12.0-150-tkg-bmq/build“
make: *** [Makefile:80: modules] Chyba 2

**Comment by Tk-Glitch** [comment]
It builds fine on my end. Make sure you have the kernel headers installed for your 5.12.0-150-tkg-bmq. `sys_close` is defined in the kernel headers so this shouldn't happen if you have them installed properly.

**Comment by pkejval** [comment]
I have headers installed. But I now recall that I compiled kernel with new option "exclude unused kernel symbols". I'll try to recompile kernel with this option disabled and let you know.

**Comment by pkejval** [comment]
Yes. It's working now! :)
