### ISSUE TITLE
The process of finding this repository without exact information

### ISSUE THREAD

**Issue by flindeberg** [Frogging-Family/nvidia-all#48]
This is a minor issue in some sense, but when I told a friend to use this repo for managing nvidia-drivers on arch he could not find the repo by googling for `tkg nvidia-all`. `nvidia-all tkg` however works better. 

On DDG the first hit for `tkg nvidia-all` is the `chaotic-aur`-clone. This repository is hit number four on DDG.

Is there some meta-information for the repository which can be altered / changed? It seems like `nvidia-tkg`, which is the old name for this repo if I understand correctly, gives better search results than `nvidia-all`.

The best search term i can come up with is `frogging family nvidia-all`, which is considerably harder to convey in speech and longer to write in a chat.

**Comment by PedroHLC** [comment]
I deleted chaotic's fork to (maybe) help with this issue...
