### ISSUE TITLE
440.100 driver fails to install

### ISSUE THREAD

**Issue by MrWissenschaft** [Frogging-Family/nvidia-all#5]
When installing 440.100 driver on 5.8.1-3-tkg-pds, DKMS produces an error. I have attached the terminal output and the make log for your perusal.

Thank you for all your hard work, and thank you in advance for looking into this for me (I only want to install it because the 450 series drivers make Final Fantasy XIV repeatedly crash lol)

[DKMS error 440-100.txt](https://github.com/Frogging-Family/nvidia-all/files/5098313/DKMS.error.440-100.txt)
[DKMS error 440-100 make log.txt](https://github.com/Frogging-Family/nvidia-all/files/5098314/DKMS.error.440-100.make.log.txt)
![Screenshot from 2020-08-19 18-53-42](https://user-images.githubusercontent.com/37015239/90671962-52ef6000-e24d-11ea-98aa-3bd20a5667a5.png)

**Comment by MrWissenschaft** [comment]
That's resolved the issue perfectly, thank you so much for your prompt response and resolution

Have a great day

**Comment by Tk-Glitch** [comment]
You're welcome :) Enjoy!
