### ISSUE TITLE
Update Nvidia 460 series 

### ISSUE THREAD

**Issue by Sultech** [Frogging-Family/nvidia-all#59]
Could you use the 460.91.03 instead of 460.84, it fixes a bug for my system where I cant use my monitor with a display port

**Comment by Tk-Glitch** [comment]
You know you can use any version not listed by using the custom option?
I'll update the 460 entry nonetheless :)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/nvidia-all/commit/452d63e0a9d9e50475a64cdf295a1069c0ca5a38
