### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Klairm** [Frogging-Family/nvidia-all#8]
How to uinstall drivers installed with this script?

**Comment by openglfreak** [comment]
The same way other packages are uninstalled...

**Comment by CodingKoopa** [comment]
You should be able to run `pacman -Qs nvidia`, pick out the `-tkg` packages, and run `pacman -Rs` for them.

**Comment by Klairm** [comment]
I did that but for some reason Nvidia drivers still there

**Comment by FLGX06** [comment]
Did you reboot? Those drivers are applied to kernel(s) using DKMS

**Comment by Klairm** [comment]
Yep, I did reboot, guess I should reinstall the system

**Comment by FLGX06** [comment]
Are you sure you are not using nouveau? Unofficial NVIDIA driver which is open source and has limitations (it is in kernel)

**Comment by Klairm** [comment]
Well now I just trying to reinstall it (because I can't get video right now) but I get dkms install returning 10 status, what's should I do?

**Comment by FLGX06** [comment]
Just for anyone wondering why @Klairm closed this, @Klairm was using old repo locally (didn't update) which had older drivers which apparently caused issues

**Comment by Klairm** [comment]
> Just for anyone wondering why @Klairm closed this, @Klairm was using old repo locally (didn't update) which had older drivers which apparently caused issues

Yep, sorry for not specify that!
