### ISSUE TITLE
NVIDIA 495 driver spamming dbus-enabled applications with invalid messages

### ISSUE THREAD

**Issue by qumaciel** [Frogging-Family/nvidia-all#82]
Please see [this thread](https://forums.developer.nvidia.com/t/bug-nvidia-v495-29-05-driver-spamming-dbus-enabled-applications-with-invalid-messages/192892).

I am also experiencing this with the latest 495 driver.

I've tried this [AUR](https://aur.archlinux.org/packages/nvidia-fake-powerd/) fix, but with no luck.

**Comment by drago-sp** [comment]
This is fixed in v510 beta:
https://forums.developer.nvidia.com/t/bug-nvidia-v495-29-05-driver-spamming-dbus-enabled-applications-with-invalid-messages/192892/39
