### ISSUE TITLE
Apparently im not the only one that has/had the issue...

### ISSUE THREAD

**Issue by Ohio2** [Frogging-Family/nvidia-all#9]
https://www.reddit.com/r/archlinux/comments/ed0d2m/i_fucked_up_my_xorg/
Just because of the nvidia-tkg (nvidia-all) drivers, i cannot start my XOrg on my linux-tkg and i think it should be both here and on the linux-tkg page.

**Comment by Ohio2** [comment]
also to note; op in the reddit comments said that he did mkinitcpio -P i also did that!

**Comment by Ohio2** [comment]
I also use arch.........

**Comment by Ohio2** [comment]
Wait i also had the same fuckin log https://pastebin.com/0AzZZUxh
like literally.

**Comment by Ohio2** [comment]
Also your driver works normally with Zen...?

**Comment by Ohio2** [comment]
I fixed this issue??? i dunno 
![image](https://user-images.githubusercontent.com/61843348/96878301-f55cd700-147a-11eb-99ca-ba2c7a38b24c.png)

**Comment by Tk-Glitch** [comment]
What am I looking at? :frog:
